### ISSUE TITLE
installed via pip3 but get an error

### ISSUE THREAD

**Issue by jamesbiasemory** [OCR-D/page-to-alto#34]
```
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (2.0.6) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/usr/local/bin/page-to-alto", line 5, in <module>
    from ocrd_page_to_alto.cli import main
  File "/usr/local/lib/python3.8/dist-packages/ocrd_page_to_alto/cli.py", line 4, in <module>
    from ocrd.decorators import ocrd_loglevel
  File "/usr/local/lib/python3.8/dist-packages/ocrd/__init__.py", line 17, in <module>
    from ocrd.processor.base import run_processor, run_cli, Processor
  File "/usr/local/lib/python3.8/dist-packages/ocrd/processor/__init__.py", line 1, in <module>
    from .base import (
  File "/usr/local/lib/python3.8/dist-packages/ocrd/processor/base.py", line 39, in <module>
    from .helpers import run_cli, run_processor, generate_processor_help # pylint: disable=unused-import
  File "/usr/local/lib/python3.8/dist-packages/ocrd/processor/helpers.py", line 13, in <module>
    from ocrd.workspace import Workspace
  File "/usr/local/lib/python3.8/dist-packages/ocrd/workspace.py", line 45, in <module>
    from .mets_server import ClientSideOcrdMets
  File "/usr/local/lib/python3.8/dist-packages/ocrd/mets_server.py", line 40, in <module>
    class OcrdAgentModel(BaseModel):
  File "/usr/local/lib/python3.8/dist-packages/pydantic/_internal/_model_construction.py", line 104, in __new__
    private_attributes = inspect_namespace(
  File "/usr/local/lib/python3.8/dist-packages/pydantic/_internal/_model_construction.py", line 345, in inspect_namespace
    raise NameError(
NameError: Fields must not use names with leading underscores; e.g., use 'type' instead of '_type'.
```

**Comment by kba** [comment]
Old (sry!) but the original problem was fixed in v2.55.2 of OCR-D/core. Should not be a problem nowadays :)
